name: "Comment Writer"
description: "Write comment in all pull request after checking"
inputs:
  correctPullRequests:
    description: "JSON that contais information of all correct open pull-requests, including their title, number and changed files"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GH_TOKEN: ${{ github.token }}
    ACTION_WORKSPACE: .github/actions/comment_writer
