name: Test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Custom action
        id: check
        uses: ./.github/actions/check-pull-requests
      - name: Custom action
        uses: ./.github/actions/actions-to-docker
        with:
          correctPullRequests: "${{ steps.check.outputs.correctPullRequests }}"
      - run: tail -f /dev/null
      # - run: echo "${{ steps.check.outputs.correctPullRequests }}"
