name: Test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Check pull requests 
        id: check
        uses: ./.github/actions/check-pull-requests
      - run: mkdir pull-request-data
      - name: Copy pull-requests files 
        uses: ./.github/actions/actions-to-docker
        with:
          correctPullRequests: "${{ steps.check.outputs.correctPullRequests }}"
        env:
          PUBLIC_SSH_KEY: "${{ secrets.PUBLIC_SSH_KEY }}"
          PRIVATE_SSH_KEY: "${{ secrets.PRIVATE_SSH_KEY }}"
      - uses: actions/checkout@v4.1.1
      - name: Run Lab
        id: result
        run: |
          labTagValue=$(echo "${{ steps.check.outputs.lab-tag }}")
          echo "$labTagValue"
          if [ "$labTagValue" == "lab1" ]; then
            uses: ./.github/actions/run-lab1
            with:
              correctPullRequests: "${{ steps.check.outputs.correctPullRequests }}"
          elif [ "$labTagValue" == "lab2" ]; then
            uses: ./.github/actions/run-lab2
            with:
              correctPullRequests: "${{ steps.check.outputs.correctPullRequests }}"
          else 
            echo no such work
          fi
      - name: Comment pull-requests
        uses: ./.github/actions/comment_writer
        with:
          correctPullRequests: "${{ steps.result.outputs.correctPullRequests }}"
