name: Test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Check pull requests 
        id: check
        uses: ./.github/actions/check-pull-requests
      - run: mkdir pull-request-data
      - name: Copy pull-requests files 
        uses: ./.github/actions/actions-to-docker
        with:
          correctPullRequests: "${{ steps.check.outputs.correctPullRequests }}"
        env:
          PUBLIC_SSH_KEY: "${{ secrets.PUBLIC_SSH_KEY }}"
          PRIVATE_SSH_KEY: "${{ secrets.PRIVATE_SSH_KEY }}"
      - uses: actions/checkout@v4.1.1
      - name: Run Metrics
        id: result
        uses: ./.github/actions/run-metrics
        with:
          correctPullRequests: "${{ steps.check.outputs.correctPullRequests }}"
      - name: Comment pull-requests
        uses: ./.github/actions/comment_writer
        with:
          correctPullRequests: "${{ steps.result.outputs.correctPullRequests }}"
      - run: tail -f /dev/null
