name: Metrics Pipeline

on:
  push:
    branches: [ main ]

jobs:
  evaluate_metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t metrics-evaluation ./actions/run-metrics

      - name: Run metrics evaluation
        run: docker run metrics-evaluation
